# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-01 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=200)),
                ('card_description', models.TextField()),
                ('card_edition', models.TextField()),
                ('card_condition', models.CharField(choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('EX', 'Excellent'), ('GD', 'Good'), ('LP', 'Lightly Played'), ('PL', 'Played'), ('P', 'Poor')], default='NM', max_length=2)),
                ('card_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=7)),
                ('listing_created_date', models.DateTimeField(auto_now_add=True)),
                ('listing_published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('listing_views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
