# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='condition',
            new_name='card_condition',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='description',
            new_name='card_description',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='edition',
            new_name='card_edition',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='card_title',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='created_date',
            new_name='listing_created_date',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='views',
            new_name='listing_views',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tag',
        ),
        migrations.AddField(
            model_name='card',
            name='listing_published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
