# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-06 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_amount',
            field=models.IntegerField(default=1),
        ),
    ]
