# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-30 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200323_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=7),
        ),
    ]
